app:
  replicas: 2
  container:
    port: "5000"
    image: ahmedsoliman202/falsk-app-api-service
  service:
    target_port: 5000
    node_port: 30008


hpa:
  enable: false
  minReplicas: 4
  maxReplicas: 10
  percentage: 50