{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-service
  labels: api-service
spec:
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: api-service
  targetCPUUtilizationPercentage: {{ .Values.hpa.percentage }}
{{- end -}}